config/routes.rb
Rails.application.routes.draw do

  root 'pages#home' # ROOT

  get 'about', to: 'pages#about', as: 'about' # RESOURCES
  get 'how', to: 'pages#how', as: 'how'
  get 'reviews', to: 'pages#reviews', as: 'reviews'
  get 'successful_signup', to: 'pages#successful_signup', as: 'successful_signup'
  get 'terms', to: 'pages#terms'
  get 'ambassadors', to: 'pages#ambassadors'
  get "newsletter", to: "pages#newsletter", as: "newsletter"

  # advisors
  get 'signup', to: 'advisors#signup', as: 'signup'
  post 'signup', to: 'advisors#signup_action', as: 'signup_action'

  # profiles
  get 'profile/:profile_id', to: 'profiles#show', as: 'show_profile'

  get 'new_profile', to: 'profiles#new_profile', as: 'new_profile'
  post 'new_profile', to: 'profiles#new_profile_action', as: "new_profile_action"

  get 'edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch 'update_profile', to: 'profiles#update', as: 'update_profile'


  # listings 
  get 'listing/:listing_id', to: 'listings#show', as: 'show_listing'
  
  get 'new_listing', to: 'listings#new_listing', as: "new_listing"
  post 'new_listing', to: 'listings#new_listing_action', as: "new_listing_action"
  
  get 'edit_listing/:listing_id', to: 'listings#edit', as: 'edit_listing'
  patch 'update_listing/:listing_id', to: 'listings#update', as: 'update_listing'

  delete 'delete_listing/:listing_id', to: 'listings#destroy', as: 'delete_listing'

  post 'question', to: 'listing_messages#create', as: 'question_message'

  # requests
  get 'request/:listing_id', to: "requests#new_request", as: 'new_request'
  post 'request/:advisor_id', to: 'requests#create_request', as: 'create_request'
  get 'request_successful', to: 'requests#successful_request', as: 'successful_request'

  # sessions
  get 'login', to: 'sessions#login', as: "login"
  post 'login', to: 'sessions#login_action', as: "login_action"
  get 'logout', to: 'sessions#logout', as: 'logout'

  # admin
  get 'admin', to: "admin_actions#admin", as: 'admin' # ADMIN
  get 'profiles_overview', to: "admin_actions#profiles_overview", as: "profiles_overview"

  get 'listings_overview', to: "admin_actions#listings_overview", as: "listings_overview"

  # advisor resources
  get 'advisors_resources/:advisor_id', to: "admin_actions#advisors_resources", as: "advisors_resources"

  # admin editing
  get 'admin_edit_profile/:profile_id', to: "admin_actions#admin_edit_profile", as: "admin_edit_profile"
  patch 'admin_update_profile', to: "admin_actions#admin_update_profile", as: "admin_update_profile"

  get "admin_edit_listing/:listing_id", to: "admin_actions#admin_edit_listing", as: "admin_edit_listing"
  patch 'admin_update_listing/:listing_id', to: "admin_actions#admin_update_listing", as: "admin_update_listing"

  # admin deletting
  delete 'destroy_advisor/:advisor_id', to: "admin_actions#destroy_advisor", as: 'admin_destroy_advisor'

  # tagging by admin
  # get "tagging", to: "admin_actions#tagging", as: "tagging"
  # post "update_tags/:listing_id", to: "admin_actions#update_tags", as: "update_tags"
  get "profile_tagging", to: "admin_actions#profile_tagging", as: "profile_tagging"
  post "update_profile_tags/:profile_id", to: "admin_actions#update_profile_tags", as: "update_profile_tags"


  # functionalities
  # contacts
  get 'contact', to: 'contact_messages#new', as: 'contact' # FUNCTIONALITIES
  get 'request_consultation', to: 'contact_messages#request_consultation', as: 'request_consultation'
  post 'contact', to: 'contact_messages#create', as: 'create_contact'
  get 'new_user_request', to: 'contact_messages#new_user_request', as: 'new_user_request'

  # pw reset
  get 'new_password_request', to: 'contact_messages#new_password_request', as: 'new_password_request'
  post 'pw_retrieval_email', to: 'contact_messages#pw_retrieval_email', as: 'pw_retrieval_email'
  
  get 'pw_reset/:pw_reset_identifier', to: 'advisors#pw_reset', as: 'pw_reset'
  patch 'pw_reset_action/:advisor_id', to: "advisors#pw_reset_action", as: "pw_reset_action"

  # search
  get "search", to: "search#get_results", as: "search"
  get "profile_search", to: "search#profile_search", as: "profile_search"

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  # association
  belongs_to :advisor

  # validations
  validates_presence_of :job_title
  validates_presence_of :description
  validates_presence_of :profile_image
  validates_presence_of :max_no_of_session
  validates_presence_of :session_price

  validate :image_upload_max_size
      
  # associate uploaded img with model
  mount_uploader :profile_image, ProfileImageUploader

  # validator for image size
  private
  def image_upload_max_size      
    if profile_image.size > 5.megabytes
      errors.add(:profile_image, "Please upload a smaller image.")
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new_profile
    if logged_in?
      @advisor = Advisor.find(session[:id])
      @profile = @advisor.profile
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  def new_profile_action
    if logged_in?
      @advisor = Advisor.find(session[:id])
      @profile = @advisor.build_profile(profile_params)
      if @profile.save
        redirect_to successful_signup_path, notice: "Success."
      else
        render 'new_profile'
      end
    else
      redirect_to login_path, notice: "Please log in."
    end 
  end

  def show
    @profile = Profile.find(params[:profile_id])
    @advisor = @profile.advisor
    @related_profiles = Profile.limit(3).order("RANDOM()")
  end

  def edit
    if logged_in?
      @advisor = Advisor.find(session[:id])
      unless @advisor.profile.nil?  
        @profile = @advisor.profile
      else 
        redirect_to login_path, notice: "You don't have a profile. Sign up again."        
      end
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  def update
    if logged_in?
      @advisor = Advisor.find(session[:id])
      @profile = @advisor.profile
      @profile.update(profile_params)
      redirect_to show_profile_path(profile_id: @profile.id), notice: "Your updated profile:"
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:description, :profile_image, :job_title, :application_help, :career_insights_help, :mentoring_help, :general_help, :session_price, :max_no_of_session, :charity_option)
  end

end

app/views/profiles/edit.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links"> 
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_path %>
    <%= link_to "How It Works", how_path %>
    <%= link_to "Logout", logout_path, class: "btn btn-small btn-turquoise" %>
  </div>
</div>

<!-- container -->
<div class="simple_container">
  <!-- edit form -->
  <div style="color: grey;"> <%= notice %> </div>  
  <div class="grey_box">
    <h3> Edit Your Settings <span style="font-size: 11px;"> - update your profile settings to your liking. </span> </h3>
      <%= form_for @profile, url: update_profile_path do |f| %>
     
      <h4> 1. About Yourself </h4>
      <h6> 1.1. Job Title / Profession </h6>
      <%= f.text_field :job_title, placeholder: "e.g. Physicist", style: "width: 358px; margin-bottom: 2px;" %>
      <h6> 1.2. Description </h6>
      <%= f.text_area :description, placeholder: "What are you currently doing? What have you done before? What are your fields of interest? etc.", style: "width: 358px; height: 197px; margin-bottom: 2px;" %>
      <h6> 1.2. Your Image </h6>
      <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png', id: "image_upload_field", style: "border: 1px solid grey; width: 358px; padding: 5px;" %>  
      <hr style="background-color: lightgrey;">

      <h4> 2. What are you willing to help with? Choose several. </h4>
      <h6> Applications - helping out people who are in the process of applying to your field. </h6> <%= f.check_box :application_help %>
      <h6> Career insight - providing insight into your profession given your personal experience. </h6> <%= f.check_box :career_insights_help %>
      <h6> Mentoring - passing on knowledge to people starting out in your field or a related one. </h6> <%= f.check_box :mentoring_help %>
      <h6> General - for requests that relate to your expertise but don't squarely fit a category. </h6> <%= f.check_box :general_help %>
      <hr style="background-color: lightgrey;">
      
      <h4> 3. What is the maximum number of requests you would be happy to get and do per week? </h4>
      <%= f.radio_button :max_no_of_session, "2", style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> 2 per week </span> <br>
      <%= f.radio_button :max_no_of_session, "1", style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> 1 per week </span> <br>
      <%= f.radio_button :max_no_of_session, "0.5", style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> 1 every 2 weeks </span> <br>
      <%= f.radio_button :max_no_of_session, "undefined" %> <span style="margin-left: 4px;"> I don't mind </span>
      <hr style="background-color: lightgrey;">

      <h4> 4. Set a price for a session - roughly 40min. of your time </h4>
      <p style="font-size: 14px; margin-top: 5px; cursor: pointer; margin-bottom: 3px; text-decoration: underline;" onclick="showSet();"> set price: </p>
      <%= f.number_field :session_price, id: "set_yourself", style: "height: 28px; width: 60px; margin-bottom: 3px;" %> <br>
      <hr style="background-color: lightgrey;">

      <h4> 5. Charity option - for those who like </h4>
      <%= f.check_box :charity_option, style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> I want the proceedings from my mentoring to go to charity. </span> <br>


      <%= f.submit "Done Editing." %>
    <% end %> 
  </div> 
  <p style="margin-top: 5px;"> Guidelighter - Made with <i class="fa fa-heart" aria-hidden="true"></i> in Barcelona </p>

</div> 

      

  

app/views/profiles/new_profile.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links"> 
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_path %>
    <%= link_to "How It Works", how_path %>
    <%= link_to "Logout", logout_path, class: "btn btn-small btn-turquoise" %>
  </div>
</div> 

<br>
<div class="simple_container">
  <!-- signup loader -->
  <div class="signup_loader">
    <%= image_tag "page-loader.gif" %>
    <p> Your account is being created ...</p>
  </div> 

  <!-- errors -->
  <% if @profile && @profile.errors.any? %>
      <h4> Try again. </h4>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul> 
  <% end %>

  <div style="color: grey; margin-bottom: 5px;"> <%= notice %> </div>

  <div style="position: relative;" class="grey_box">
    <h6 style="position: absolute; top: -4px; right: 7px;"> 2/2 </h6>
    <h2 style="margin-bottom: 24px;"> Become a guide - All you have to do. <span style="font-size: 11px;">  </span> </h2>

    <!-- form -->
    <%= form_for :profile, path: new_profile_action_path, html: { multipart: true } do |f|%>
      
      <h4> 1. About Yourself </h4>
      <h6> 1.1. Job Title / Profession </h6>
      <%= f.text_field :job_title, placeholder: "Physicist? Teacher?", style: "width: 358px; margin-bottom: 2px;" %>
      <h6> 1.2. Description </h6>
      <%= f.text_area :description, placeholder: "What are you currently doing? What have you done before? What are your fields of expertise and interest? etc.", style: "width: 358px; height: 197px; margin-bottom: 2px;" %>
      <h6> 1.2. Your Image </h6>
      <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png', id: "image_upload_field", style: "border: 1px solid grey; width: 358px; padding: 5px;" %>  
      <hr style="background-color: lightgrey;">
      
      <h4> 2. What are you willing to help with? Choose several </h4>
      <h6> Applications - helping out people who are in the process of applying to your field. </h6> <%= f.check_box :application_help, checked: true %>
      <h6> Career insight - providing insight into your profession given your personal experience. </h6> <%= f.check_box :career_insights_help, checked: true %>
      <h6> Mentoring - passing on knowledge to people starting out in your field or a related one. </h6> <%= f.check_box :mentoring_help, checked: true %>
      <h6> General - for requests that relate to your expertise but don't squarely fit a category. </h6> <%= f.check_box :general_help, checked: true %>
      <hr style="background-color: lightgrey;">
      
      <h4> 3. What is the maximum number of requests you would be happy to get and do per week? </h4>
      <%= f.radio_button :max_no_of_session, "2", style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> 2 per week </span> <br>
      <%= f.radio_button :max_no_of_session, "1", :checked => true, style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> 1 per week </span> <br>
      <%= f.radio_button :max_no_of_session, "0.5", style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> 1 every 2 weeks </span> <br>
      <%= f.radio_button :max_no_of_session, "undefined" %> <span style="margin-left: 4px;"> I don't mind </span>
      <hr style="background-color: lightgrey;">

      <h4> 4. Set a price for a session - roughly 40min. of your time</h4>
      
      <p style="font-size: 14px; margin-top: 5px; cursor: pointer; margin-bottom: 3px; text-decoration: underline;" onclick="showSet();"> set an exact price </p>
      <%= f.number_field :session_price, id: "set_yourself", style: "height: 28px; width: 60px; margin-bottom: 3px;" %> <br> <span style="text-decoration: underline;"> choose a standard </span> <br>
      <%= f.radio_button :session_price, 15, class: "session_price", id: "session_price" %> £ 15  <br>
      <%= f.radio_button :session_price, 20, class: "session_price" %> £ 20 <br>
      <%= f.radio_button :session_price, 25, :checked => true, id: "default_checked", class: "session_price" %> £ 25 <br>
      <%= f.radio_button :session_price, 35, class: "session_price" %> £ 35 <br>
      <%= f.radio_button :session_price, 50, class: "session_price"%> £ 50 <br>
      
      <div style="margin-top: 16px;"> Why a price? <br> Guidelighter is built on the notion of openly sharing one's experience and expertise with those who can benefit from it. Yet we believe that the time and energy of capable people is valuable and that this is to be respected and honoured. Thus, a session price should be set. </div>
      <hr style="background-color: lightgrey;">

      <h4> 5. Charity option - for those who like </h4>
      <%= f.check_box :charity_option, style: "margin-bottom: 9px;" %> <span style="margin-left: 4px;"> I want the proceedings from my mentoring to go to charity. </span> <br>

      <%= f.submit "Done.", id: "std-btn", style: "padding: 14px 213px;" %> 
    <% end %>
  </div>

  <p id="love" style="margin-top: 10px;"> Guidelighter - Made with <i class="fa fa-heart" aria-hidden="true"></i> in Barcelona </p>

  <!-- Options for extension:
    - add offer out of the ordinary in 1
    - set your own price field in 3
    - add a max number of sessions section as section 4
    - obv: put into a wizard. 
  -->

  <!-- <div style="height: 40px; background-color: #FFD990; line-height: 40px; text-align: center;" >
    See example-profiles below
  </div> <br> --> <br> <br>
</div>


<script type="text/javascript">
  // removing loader
  $(window).load(function() {
    $(".signup_loader").delay(1320).fadeOut("slow");
  })

  // alert if large uploads
  $('#image_upload_field').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Please upload a smaller file.');
    }
  });

  // uncheck radio buttons when number field has focus
  $('#set_yourself').focus(function () {
    $('.session_price').removeAttr("checked");
  });

  // uncheck radio buttons when number field has a value
  if($('#set_yourself').val().length != 0){
    $('.session_price').removeAttr("checked");
  }

  // blanking number field when radio button is checked
  $(".session_price").change(function(){
    $("#set_yourself").val('');
  });
</script>

app/views/profiles/show.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links">
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_path %>
    <%= link_to "How it works", how_path %>
    <%= link_to "Success Stories", reviews_path, class: "btn white_border", style: "margin-left: 8px; padding: 5px 28px; border: 1px solid white;" %>
  </div>
</div>

<!-- content -->
<div class="simple_container">
  <div class="color_background"> </div>
  
  <div class="btn-on-show" style="text-align: center; width: 332px;">
    <!-- <div onclick="goBack();" class="btn" style="border: 1px solid black; padding: 14px 72px; margin-top: 2px;"> MORE GUIDES </div> -->
    <div onclick="goBack();" class="btn" style="border: 1px solid black; padding: 23px 63px; margin-top: 4px;"> GO BACK TO KEEP BROWSING </div>
    <!-- <div onclick="goBack();" class="btn" style="border: 1px solid black; padding: 12px 88px; margin-top: 4px;"> GO BACK </div> -->
  </div>

  <div style="color: grey; margin-bottom: 5px;"> <%= notice %> </div>
  <h6 style="font-size: 15px; text-decoration: underline;"> <%= @advisor.first_name %> <%= @advisor.second_name[0] %> / Your Guide </h6>
  <%= image_tag @profile.profile_image.url, style: "border: 1px solid #A6A6A6; margin-top: 7px; margin-bottom: 3px;" %> <br>



  <div id="guide_show" style="margin-bottom: 5px; margin-top: 15px;">
    <h6 style="font-size: 15px; text-decoration: underline;"> <%= @advisor.first_name %> <%= @advisor.second_name[0] %>. </h6>

    <div class="" style="padding: 4px 52px 8px 52px; text-align: center; font-size: 15px; padding: 0 0 8px 0; margin-bottom: 10px;">
    Applications Help
    <% if @profile.application_help? %> 
      <i class="fa fa-check" aria-hidden="true" style="color: grey;"></i> 
    <% else %>
      <i class="fa fa-times" aria-hidden="true" style="color: grey;"></i>
    <% end %>

    Career Support
    <% if @profile.career_insights_help? %>  
      <i class="fa fa-check" aria-hidden="true" style="color: grey;"></i> 
    <% else %>
      <i class="fa fa-times" aria-hidden="true" style="color: grey;"></i>
    <% end %> <br>
    
    Mentoring
    <% if @profile.mentoring_help? %> 
      <i class="fa fa-check" aria-hidden="true" style="color: grey;"></i> 
     <% else %>
      <i class="fa fa-times" aria-hidden="true" style="color: grey;"></i>
     <% end %>
    
    Specific Requests
    <% if @profile.general_help? %> 
      <i class="fa fa-check" aria-hidden="true" style="color: grey;"></i> 
    <% else %>
      <i class="fa fa-times" aria-hidden="true" style="color: grey;"></i>
    <% end %>
    </div>
  


    <div class="grey_box" style="padding: 4px 52px 8px 52px;">
      <h3> <span style="font-size: 19px;"> <%= @profile.job_title if @profile.job_title %> </span> </h3>
      <p> <%= simple_format @profile.description, style: "line-height: 1.5; font-size: 15px;" %> </p>
      <h6 style="font-size: 15px;"> Session: £ <%= @profile.session_price if @profile.session_price %> </h6>
      <div class="button">
        <a id="std-btn" style="font-size: 18px; background-color: #DFCFB6; padding: 22px 129px; cursor: pointer;" onclick="showRequest();" return false;> Request <%= @advisor.first_name %> </a>
      </div>
    </div>
  </div>

  <div id="request_from" style="display: none;">
    <div class="grey_box" style="margin-bottom: 5px;">  
      <!-- <h3> Request Form </h3> -->
      <h4 style="margin-top: 17px; margin-bottom: -13px; text-decoration: underline;"> Request Form </h4>
      <%= form_for :request, url: create_request_path(advisor_id: @advisor.id) do |f| %>
        <h6 style="margin-top: 18px;"> Briefly, what is your situation? What would you like help with? <br> </h6>
        <%= f.text_field :indicated_interest , style: "width: 418px;", class: "small_placeholder_text" %>
        <h6>When would you usually be available for a session? Days? Times? </h6>
        <%= f.text_field :requesting_availability, style: "width: 418px;", class: "small_placeholder_text" %>
        <h6>Your Email - so we can reply. </h6>
        <%= f.text_field :requesting_email, style: "width: 418px;", class: "small_placeholder_text" %>
        <h6>Your Name - for a personal touch. </h6>
        <%= f.text_field :requesting_name, style: "width: 418px;", class: "small_placeholder_text" %>
        <%= f.hidden_field :advisor_id, value: @advisor.id %>
        <%= f.submit "Done.", id: "std-btn" %> <br>
        <h6> Note: This request is not binding. It's purpose is to check whether it <br> is possible to arrange a session with the guide you are requesting. </h6>
      <% end %>     
    </div>
  </div>

  <% if @profile.max_no_of_session %> 
    <div style="height: 40px; background-color: #FFD990; line-height: 40px; text-align: center; font-size: 15px;">
      <% if @profile.max_no_of_session == "undefined" %>
        Currently available: <i class="fa fa-check" aria-hidden="true"></i>
      <% else %>
        Max. requests per week: <%= @profile.max_no_of_session %> | Currently available: <i class="fa fa-check" aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>

  <h6 style="font-size: 15px; text-decoration: underline; margin-top: 12px;"> What <%= @advisor.first_name %> is offering: </h6>
  <div id="offering" style="margin-top: 5px;">
    <div class="grey_box" style="padding: 14px 52px 14px 52px;">
      <!-- <h4 style="font-size: 19px;"> What <%= @advisor.first_name %> can help with </h4> -->
      <ul style="margin-left: -20px; margin-top: -3px; margin-bottom: -6px;">
        <% if @profile.application_help? %> <li> <h6 style="font-size: 15px;"> Applications Help - if you are currently applying to or are planning to apply to <%= @advisor.first_name %>'s career path, make sure to get in touch to get some valuable help. </h6> </li> <% end %>
        <% if @profile.career_insights_help? %> <li> <h6 style="font-size: 15px;"> Career Support - if you are interested in gaining insight into <%= @advisor.first_name %>'s career path to see what it's all about, how it works and how to progress. </h6> </li> <% end %>
        <% if @profile.mentoring_help? %> <li> <h6 style="font-size: 15px;"> Mentoring - if you are interested in acquiring some of the skills - hard and soft - that faciltate success in <%= @advisor.first_name %>'s occupation. </h6> </li> <% end %>
        <% if @profile.general_help? %> <li> <h6 style="font-size: 15px;"> Specific Requests </span> - anything that would help you out that directly or indirectly relates to <%= @advisor.first_name %>'s expertise. You choose. What do you need? </h6> </li> <% end %>
      </ul>
      <div class="button" style="margin-top: 20px;">
        <a id="std-btn" style="font-size: 18px; background-color: #DFCFB6; padding: 21px 100px; cursor: pointer;" onclick="showRequestBottom();" return false;> Request <%= @advisor.first_name %> </a>
      </div>
    </div>
  </div>

  <div id="request_from_bottom" style="display: none; margin-top: 10px;">
    <div class="grey_box" style="margin-bottom: 5px;">  
      <!-- <h3> Request Form </h3> -->
      <h4 style="margin-top: 17px; margin-bottom: -13px; text-decoration: underline;"> Request Form </h4>
      <%= form_for :request, url: create_request_path(advisor_id: @advisor.id) do |f| %>
        <h6 style="margin-top: 18px;"> Briefly, what is your situation? What would you like help with? <br> </h6>
        <%= f.text_field :indicated_interest , style: "width: 418px;", class: "small_placeholder_text" %>
        <h6>When would you usually be available for a session? Days? Times? </h6>
        <%= f.text_field :requesting_availability, style: "width: 418px;", class: "small_placeholder_text" %>
        <h6>Your Email - so we can reply. </h6>
        <%= f.text_field :requesting_email, style: "width: 418px;", class: "small_placeholder_text" %>
        <h6>Your Name - for a personal touch. </h6>
        <%= f.text_field :requesting_name, style: "width: 418px;", class: "small_placeholder_text" %>
        <%= f.hidden_field :advisor_id, value: @advisor.id %>
        <%= f.submit "Done.", id: "std-btn" %> <br>
        <h6> Note: This request is not binding. It's purpose is to check whether it <br> is possible to arrange a session with the guide you are requesting. </h6>
      <% end %>     
    </div>
  </div>

  <div onclick="goBack();" onhover="style.color = red;" class="btn" style="border: 1px solid lightGrey; padding: 23px 63px; width: 100%; margin-top: 10px;"> GO BACK TO KEEP BROWSING </div>

  <p id="love" style="margin-top: 5px; cursor: pointer; margin-bottom: 5px;" onclick="showQuestions();"> Any Questions? Click here to ask. </p>

  <div id="questions" style="display: none;">
    <div class="grey_box" style="padding: 20px 52px 8px 52px;">
      <%= form_for :message, url: question_message_path do |f| %> 
        <%= f.text_area :content, placeholder: "your question", style: "height: 72px;" %>
        <%= f.text_field :reply_address, placeholder: "your@email.com", style: "width: 100%;" %> <br>
        <%= f.hidden_field :advisor_id, value: @advisor.id %>
        <div class="button" style="padding-top: 0px;"> 
          <%= f.submit "Ask", style: "padding: 2px 30px;", id: "std-btn" %>
        </div>
      <% end %>
    </div> <br>
  </div>

  <div class="bottom_right_buttons_home">
    <%= link_to "Can't find what you are looking for?", new_user_request_path, class: "btn btn-md", style: "width: 264px;" %> <br>
  </div>
  
</div>

<!-- js for back button -->
<script type="text/javascript">
  function goBack(){
    window.history.back()
  }

  function showRequest(){
    $("#request_from").toggle();
  }

 function showRequestBottom(){
    $("#request_from_bottom").toggle();
  }

  function showQuestions(){
    $("#questions").toggle();
  }
</script>