config/routes.rb
Rails.application.routes.draw do

  root 'pages#home' # ROOT

  get 'about', to: 'pages#about', as: 'about' # RESOURCES
  get 'how', to: 'pages#how', as: 'how'
  get 'reviews', to: 'pages#reviews', as: 'reviews'
  get 'successful_signup', to: 'pages#successful_signup', as: 'successful_signup'
  get 'terms', to: 'pages#terms'
  get 'ambassadors', to: 'pages#ambassadors'
  get "newsletter", to: "pages#newsletter", as: "newsletter"

  # advisors
  get 'signup', to: 'advisors#signup', as: 'signup'
  post 'signup', to: 'advisors#signup_action', as: 'signup_action'

  # profiles
  get 'profile/:profile_id', to: 'profiles#show', as: 'show_profile'

  get 'new_profile', to: 'profiles#new_profile', as: 'new_profile'
  post 'new_profile', to: 'profiles#new_profile_action', as: "new_profile_action"

  get 'edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch 'update_profile', to: 'profiles#update', as: 'update_profile'


  # listings 
  get 'listing/:listing_id', to: 'listings#show', as: 'show_listing'
  
  get 'new_listing', to: 'listings#new_listing', as: "new_listing"
  post 'new_listing', to: 'listings#new_listing_action', as: "new_listing_action"
  
  get 'edit_listing/:listing_id', to: 'listings#edit', as: 'edit_listing'
  patch 'update_listing/:listing_id', to: 'listings#update', as: 'update_listing'

  delete 'delete_listing/:listing_id', to: 'listings#destroy', as: 'delete_listing'

  post 'question', to: 'listing_messages#create', as: 'question_message'

  # requests
  get 'request/:listing_id', to: "requests#new_request", as: 'new_request'
  post 'request/:advisor_id', to: 'requests#create_request', as: 'create_request'
  get 'request_successful', to: 'requests#successful_request', as: 'successful_request'

  # sessions
  get 'login', to: 'sessions#login', as: "login"
  post 'login', to: 'sessions#login_action', as: "login_action"
  get 'logout', to: 'sessions#logout', as: 'logout'

  # admin
  get 'admin', to: "admin_actions#admin", as: 'admin' # ADMIN
  get 'profiles_overview', to: "admin_actions#profiles_overview", as: "profiles_overview"

  get 'listings_overview', to: "admin_actions#listings_overview", as: "listings_overview"

  # advisor resources
  get 'advisors_resources/:advisor_id', to: "admin_actions#advisors_resources", as: "advisors_resources"

  # admin editing
  get 'admin_edit_profile/:profile_id', to: "admin_actions#admin_edit_profile", as: "admin_edit_profile"
  patch 'admin_update_profile', to: "admin_actions#admin_update_profile", as: "admin_update_profile"

  get "admin_edit_listing/:listing_id", to: "admin_actions#admin_edit_listing", as: "admin_edit_listing"
  patch 'admin_update_listing/:listing_id', to: "admin_actions#admin_update_listing", as: "admin_update_listing"

  # admin deletting
  delete 'destroy_advisor/:advisor_id', to: "admin_actions#destroy_advisor", as: 'admin_destroy_advisor'

  # tagging by admin
  # get "tagging", to: "admin_actions#tagging", as: "tagging"
  # post "update_tags/:listing_id", to: "admin_actions#update_tags", as: "update_tags"
  get "profile_tagging", to: "admin_actions#profile_tagging", as: "profile_tagging"
  post "update_profile_tags/:profile_id", to: "admin_actions#update_profile_tags", as: "update_profile_tags"


  # functionalities
  # contacts
  get 'contact', to: 'contact_messages#new', as: 'contact' # FUNCTIONALITIES
  get 'request_consultation', to: 'contact_messages#request_consultation', as: 'request_consultation'
  post 'contact', to: 'contact_messages#create', as: 'create_contact'
  get 'new_user_request', to: 'contact_messages#new_user_request', as: 'new_user_request'

  # pw reset
  get 'new_password_request', to: 'contact_messages#new_password_request', as: 'new_password_request'
  post 'pw_retrieval_email', to: 'contact_messages#pw_retrieval_email', as: 'pw_retrieval_email'
  
  get 'pw_reset/:pw_reset_identifier', to: 'advisors#pw_reset', as: 'pw_reset'
  patch 'pw_reset_action/:advisor_id', to: "advisors#pw_reset_action", as: "pw_reset_action"

  # search
  get "search", to: "search#get_results", as: "search"
  get "profile_search", to: "search#profile_search", as: "profile_search"

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  # association
  belongs_to :advisor
  has_many :requests

  # validations
  validates_presence_of :title, :description, :price
  validate :image_upload_max_size

  # associate uploaded image with model
  mount_uploader :listing_image, ListingImageUploader

  # validator for img size
  private
  def image_upload_max_size
    if listing_image.size > 5.megabytes
      errors.add(:listing_image, "Please upload a smaller image.")
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def show
    @listing = Listing.find(params[:listing_id])
    @advisor = @listing.advisor
    @profile = @advisor.profile
  end

  def new_listing
    if logged_in?
      @advisor = Advisor.find(session[:id])
      @profile = @advisor.profile
      @listings = @advisor.listings
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  def new_listing_action
    if logged_in?
      @advisor = Advisor.find(session[:id])
      @listing = @advisor.listings.build(listing_params)
      if @listing.save
        redirect_to new_listing_path, notice: "√ Your offer has been published successfully. Post another one?"
      else
        render 'new_listing'
      end
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  def edit
    if logged_in?
      @listing = Listing.find(params[:listing_id])
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  def update
    if logged_in?
      @listing = Listing.find(params[:listing_id])
      @listing.update(listing_params)
      redirect_to new_listing_path, notice: "The Listing has been updated."
    else
      redirect_to login_path, notice: "Please log in."
    end
  end

  def destroy
    if logged_in?
      @listing = Listing.find(params[:listing_id])
      @listing.delete
      redirect_to new_listing_path, notice: "The Listing has been deleted."
    else
      redirect_to login_path, notice: "Please log in."
    end      
  end

  private
  def listing_params
    params.require(:listing).permit(:title, :description, :price, :listing_image)
  end
  
end

app/views/listings/edit.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links">  
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_path %>
    <%= link_to "How It Works", how_path %>
    <%= link_to "Logout", logout_path, class: "btn btn-small btn-turquoise" %>
  </div>
</div>

<!-- container -->
<div class="simple_container">
  <!-- form -->
  <div class="grey_box">
    <h3>Edit Listing</h3>
    <%= form_for @listing, url: update_listing_path(listing_id: @listing.id) do |f| %>
      <%= f.text_field :title %>
      <%= f.text_area :description, style: "height: 225px;" %>
      <%= f.number_field :price %> <br>
      <%= f.submit "Done." %>
    <% end %>
  </div>
  <!-- love -->
  <div class="with_love">
    Made with <i class="fa fa-heart" aria-hidden="true"></i> in Barcelona
  </div>
</div>

app/views/listings/new_listing.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links">
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_path %>
    <%= link_to "How It Works", how_path %>
    <%= link_to "Logout", logout_path, class: "btn btn-small btn-turquoise" %>
  </div>
</div>


<div class="simple_container">
  <!-- errors -->
  <% if @listing && @listing.errors.any? %>
    <h4> Try again. </h4>
    <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul> 
  <% end %>
  <!-- new listing -->
  <div style="color: grey; margin-bottom: 5px;"> <%= notice %> </div>
  <h6 style="text-decoration: underline;"> Decide on your offers. </h6>
  <div class="grey_box">
    <h3> What would you like to share on Guidelighter? </h3>
    <%= form_for :listing, path: new_listing_action_path, html: { multipart: true } do |f| %>
      <%= f.hidden_field :advisor_id, :value => @advisor.id %>
      <h6> Many people share something related to their professional expierence, knowledge and skills. For some inspiration, have a look at the examples at the bottom.</h6>
      <%= f.text_field :title, placeholder: "Title" %>
      <%= f.text_area :description, placeholder: "Description", style: "width: 355px; height: 190px;" %>
      <%= f.number_field :price, placeholder: "Price per session (in £)", min: "0", style: "width: 165px;" %> 
      <span style="font-size: 11px;"> Currency: British pounds. </span>
      <%= f.submit "Done." %>
    <% end %> 
  </div> 
  <div style="height: 40px; background-color: #FFD990; line-height: 40px; text-align: center;" >
    See example-offers below
  </div> <br>
  <!-- manage listings -->
  <% if !@listings.nil? %>
    <% if !@listings.empty? %>
      <h3> Manage Your Listings <span style="font-size: 11px;"> </span> </h3> <br>
      <% @listings.each do |listing| %>
        <div class="listing_on_new">
          <br>
          <% unless listing.title.empty? %>
            Title: <%= listing.title %>
          <% end %> <br> <br>
          
          <% unless listing.description.empty? %>
            Description: <%= simple_format listing.description %>
          <% end %> <br> <br>
          
          <% unless listing.price.nil? %>
            Price: <%= listing.price %> £
          <% end %>

          <% unless listing.listing_image.url.nil? %>  
            <%= image_tag listing.listing_image.url %>
          <% end %> <br>

          <div class="links" style="color: lightGrey;">
            <%= link_to "Edit", edit_listing_path(listing_id: listing.id) %> |
            <%= link_to "Delete", delete_listing_path(listing_id: listing.id), method: :delete, data: { confirm: 'Want to delete this listing?' } %>
          </div>

        </div> <br>
      <% end %>
    <% end %>
  <% end %>

  <h3> Examples </h3>

  <h5 style="text-decoration: underline;"> Guide: Oleg Giberstein </h5>
  <div class="example_listing grey_box" style="padding: 20px 35px; margin-bottom: 25px; background-color: #F7F7F7;">
    <h4> Advice on Finance Careers & Applications </h4>
    <div>
     Are you considering to apply for jobs in finance but are not sure where to start? I have worked in Private Banking, Corporate Banking and Sovereign Risk at Citigroup for 4 years. I can share my experience of working in different areas of finance and help you to get a grasp of what goes on where and how you can get in (and whether you should). <br> <br> In case you already know what you are interested in, I can guide you through the most important issues and what you should know before applying. <br> <br> We can communicate via Skype or in person (if we can arrange it.
    </div> <br>
    <div>Price: 30 £</div>
    <%= image_tag 'oleg.jpg' %>
  </div>

  <div class="example_listing grey_box" style="padding: 20px 35px; margin-bottom: 25px; background-color: #F7F7F7;">
    <h4> CV / Personal Statement Reviews & Help </h4>
    <div>
    I can review your personal statements, cover letters and CVs and help you take them onto the next level. My experience is based on successfully applying for degrees at Oxford, Cambridge, the LSE and UCL as well as for jobs at organisations like Citi, Goldman Sachs, McKinsey or Boston Consulting. <br> <br> You can send me your material and I will go through it, provide comments, suggestions and talk you through it. We can communicate via email and Skype. <br> <br> If you are unsure whether to proceed, book my free listing first and we can have an intro chat!
    </div> <br>
    <div>Price: 30 £</div>
    <%= image_tag 'oleg.jpg' %>
  </div>

  <h5 style="text-decoration: underline;"> Guide: Johannes Seikowsky </h5>
  <div class="example_listing grey_box" style="padding: 20px 35px; margin-bottom: 25px; background-color: #F7F7F7;">
    <h4> Oxbridge Interview preparation </h4>
    <div>
     I did my BA at the University of Oxford in "Economics and Management" (E&M). As one would expect, I had to go through the official application and interview process (which is similar to the Cambridge one). As a result I can help out by sharing my experience and knowledge of the Oxbridge application process and give useable advice related to it. This is valuable in the general case irrespective of what course you're applying to. Knowing what awaits you in general will sooth your mind. Evidently I can help out even more if you are applying for courses that have an Economics component (like PPE for example). Good luck to all of you and feel free to get in touch.
    </div> <br>
    <div>Price: 25 £</div>
    <%= image_tag 'johannes.jpg' %>
  </div>

  <div class="example_listing grey_box" style="padding: 20px 35px; margin-bottom: 25px; background-color: #F7F7F7;">
    <h4> Mentoring for beginning programmers </h4>
    <div>
      I'm the CTO of Guidelighter, which means I do all the development and technical stuff around here. Despite this role I have never had any formal education in Computer science whatsoever and mostly taught myself through trial and error. Therefore I know how hard and how frustrating it can be to wiggle yourself through the stages of becoming a competent programmer. And that's why I offer my support in this regard. Either in the form of specific one-off support sessions when you need them or in a more continuous format, like monthly or bi-weekly mentoring sessions. That is up to you. If you are interested in this principal offering, just get in touch and we'll figure out the details together.
    </div> <br>
    <div>Price: 35 £</div>
    <%= image_tag 'johannes.jpg' %>
  </div> 

  <h5 style="text-decoration: underline;"> Guide: Surojoit Chakraverti </h5>
  <div class="example_listing grey_box" style="padding: 20px 35px; margin-bottom: 25px; background-color: #F7F7F7;">
    <h4> Getting into banking for students with a non-finance background </h4>
    <div>
      I will help you refine your story and effectively communicate your unique skill set for typical qualitative interviews for roles in IBD.
      <br> <br>
      Grab a coffee or discuss over a call (typically 30 minutes).
    </div> <br>
    <div>Price: 25 £</div>
    <%= image_tag 'suro.jpg' %>
  </div>

  <div class="example_listing grey_box" style="padding: 20px 35px; margin-bottom: 25px; background-color: #F7F7F7;">
    <h4> Choosing the right M&A team </h4>
    <div>
      Having worked for c.4 years across Industrials and Healthcare M&A at Citigroup and Rothschild, I can provide an insight into the experience, skill set, technical skills and perspectives across different sector and product coverage teams.
      <br> <br>
      Grab a coffee or over the phone (c.30 minutes)
    </div> <br>
    <div>Price: 35 £</div>
    <%= image_tag 'suro.jpg' %>
  </div>


</div>

<!-- alerting large uploads -->
<script type="text/javascript">
  $('#image_upload_field').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Please upload a smaller file.');
    }
  });
</script>

app/views/listings/show.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links">
    <%= link_to "About Us", about_path %>
    <%= link_to "Contact Us", contact_path %>
    <%= link_to "How it works", how_path %>
    <%= link_to "What people say", reviews_path %>
    <%= link_to "Become a Guide in 3 Minutes", signup_path, class: "btn white_border", style: "margin-left: 8px; padding: 5px 28px;" %>
  </div>
</div>

<!-- content -->
<div class="simple_container">
  <div class="color_background"> </div>
  
  <div class="btn-on-show">
    <%= link_to "Back", "#", onclick: "goBack();", class: "btn btn-md" %>
    <%= link_to "Browse more Listings", search_path(), class: "btn btn-md" %> <br>
  </div>

  <div style="color: grey; margin-bottom: 5px;"> <%= notice %> </div>
  <h6> <%= @advisor.first_name %> <%= @advisor.second_name[0] %>. / your guide </h6>
  <%= image_tag @profile.profile_image.url, style: "border: 1px solid #A6A6A6;"  %> <br>

  <!-- <h6> The Offer </h6>
  <div class="grey_box" style="padding: 4px 52px 20px 52px;">
    <h3> <%= @listing.title %> </h3>
    <p> <%= simple_format @listing.description, style: "line-height: 1.5;" %> </p>
    <p style="font-size: 15px; text-decoration: underline; margin-bottom: 0px;">Price: <%= @listing.price %> £ </p>
    <div class="button">
      <%= link_to "Request Guide", new_request_path(listing_id: @listing.id), style: "padding: 15px 58px;", id: "std-btn" %>
    </div>
  </div> <br> -->

  <div class="grey_box" style="padding: 4px 52px 8px 52px;">
    <h3> <%= @advisor.first_name %> <%= @advisor.second_name[0] %>.  </h3>
    <p> <%= simple_format @profile.description, style: "line-height: 1.5;" %> </p>
    <div class="button">
      <%= link_to "Request Guide", new_request_path(listing_id: @listing.id), style: "padding: 19px 100px;", id: "std-btn" %>
    </div>
  </div> <br>

  <div id="questions">
    <h6> Questions? </h6>
    <div class="grey_box" style="padding: 14px 52px 8px 52px;">
      <br>
      <%= form_for :message, url: question_message_path do |f| %> 
        <%= f.text_area :content, placeholder: "your question", style: "height: 72px;" %>
        <%= f.text_field :reply_address, placeholder: "your@email.com", style: "width: 100%;" %> <br>
        <%= f.hidden_field :advisor_id, value: @advisor.id %>
        <div class="button" style="padding-top: 0px;"> 
          <%= f.submit "Ask", style: "padding: 2px 30px;", id: "std-btn" %>
        </div>
      <% end %>
    </div> <br>
  </div>

  <div class="bottom_right_buttons_home">
    <%= link_to "Mentoring", search_path(category: "practical_expertise"), class: "btn btn-md" %> <br>
    <%= link_to "Career Help", search_path(category: "career_insights"), class: "btn btn-md" %> <br>
    <%= link_to "Applications", search_path(category: "application_help"), class: "btn btn-md" %> <br>
  </div>

  <!-- <div class="bottom_right_buttons">
    <%= link_to "Submit a request", new_user_request_path, class: "btn btn-md" %>
  </div> -->

  <p> Guidelighter - Made with <i class="fa fa-heart" aria-hidden="true"></i> in Barcelona </p>
</div>

<!-- js for back button -->
<script type="text/javascript">
  function goBack(){
    window.history.back()
  }
</script>