config/routes.rb
Rails.application.routes.draw do

  root 'pages#home' # ROOT

  get 'about', to: 'pages#about', as: 'about' # RESOURCES
  get 'how', to: 'pages#how', as: 'how'
  get 'reviews', to: 'pages#reviews', as: 'reviews'
  get 'successful_signup', to: 'pages#successful_signup', as: 'successful_signup'
  get 'terms', to: 'pages#terms'
  get 'ambassadors', to: 'pages#ambassadors'
  get "newsletter", to: "pages#newsletter", as: "newsletter"

  # advisors
  get 'signup', to: 'advisors#signup', as: 'signup'
  post 'signup', to: 'advisors#signup_action', as: 'signup_action'

  # profiles
  get 'profile/:profile_id', to: 'profiles#show', as: 'show_profile'

  get 'new_profile', to: 'profiles#new_profile', as: 'new_profile'
  post 'new_profile', to: 'profiles#new_profile_action', as: "new_profile_action"

  get 'edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch 'update_profile', to: 'profiles#update', as: 'update_profile'


  # listings 
  get 'listing/:listing_id', to: 'listings#show', as: 'show_listing'
  
  get 'new_listing', to: 'listings#new_listing', as: "new_listing"
  post 'new_listing', to: 'listings#new_listing_action', as: "new_listing_action"
  
  get 'edit_listing/:listing_id', to: 'listings#edit', as: 'edit_listing'
  patch 'update_listing/:listing_id', to: 'listings#update', as: 'update_listing'

  delete 'delete_listing/:listing_id', to: 'listings#destroy', as: 'delete_listing'

  post 'question', to: 'listing_messages#create', as: 'question_message'

  # requests
  get 'request/:listing_id', to: "requests#new_request", as: 'new_request'
  post 'request/:advisor_id', to: 'requests#create_request', as: 'create_request'
  get 'request_successful', to: 'requests#successful_request', as: 'successful_request'

  # sessions
  get 'login', to: 'sessions#login', as: "login"
  post 'login', to: 'sessions#login_action', as: "login_action"
  get 'logout', to: 'sessions#logout', as: 'logout'

  # admin
  get 'admin', to: "admin_actions#admin", as: 'admin' # ADMIN
  get 'profiles_overview', to: "admin_actions#profiles_overview", as: "profiles_overview"

  get 'listings_overview', to: "admin_actions#listings_overview", as: "listings_overview"

  # advisor resources
  get 'advisors_resources/:advisor_id', to: "admin_actions#advisors_resources", as: "advisors_resources"

  # admin editing
  get 'admin_edit_profile/:profile_id', to: "admin_actions#admin_edit_profile", as: "admin_edit_profile"
  patch 'admin_update_profile', to: "admin_actions#admin_update_profile", as: "admin_update_profile"

  get "admin_edit_listing/:listing_id", to: "admin_actions#admin_edit_listing", as: "admin_edit_listing"
  patch 'admin_update_listing/:listing_id', to: "admin_actions#admin_update_listing", as: "admin_update_listing"

  # admin deletting
  delete 'destroy_advisor/:advisor_id', to: "admin_actions#destroy_advisor", as: 'admin_destroy_advisor'

  # tagging by admin
  # get "tagging", to: "admin_actions#tagging", as: "tagging"
  # post "update_tags/:listing_id", to: "admin_actions#update_tags", as: "update_tags"
  get "profile_tagging", to: "admin_actions#profile_tagging", as: "profile_tagging"
  post "update_profile_tags/:profile_id", to: "admin_actions#update_profile_tags", as: "update_profile_tags"


  # functionalities
  # contacts
  get 'contact', to: 'contact_messages#new', as: 'contact' # FUNCTIONALITIES
  get 'request_consultation', to: 'contact_messages#request_consultation', as: 'request_consultation'
  post 'contact', to: 'contact_messages#create', as: 'create_contact'
  get 'new_user_request', to: 'contact_messages#new_user_request', as: 'new_user_request'

  # pw reset
  get 'new_password_request', to: 'contact_messages#new_password_request', as: 'new_password_request'
  post 'pw_retrieval_email', to: 'contact_messages#pw_retrieval_email', as: 'pw_retrieval_email'
  
  get 'pw_reset/:pw_reset_identifier', to: 'advisors#pw_reset', as: 'pw_reset'
  patch 'pw_reset_action/:advisor_id', to: "advisors#pw_reset_action", as: "pw_reset_action"

  # search
  get "search", to: "search#get_results", as: "search"
  get "profile_search", to: "search#profile_search", as: "profile_search"

end

app/views/pages/about.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links">
    <%= link_to "How it works", how_path %>
    <%= link_to "Success Stories", reviews_path %>
    <%= link_to "Blog", "https://medium.com/guidelighter", target: "_blank" %> 
    <%= link_to "Terms & Conditions", terms_path %>

    <% if logged_in? %>
      <%= link_to "Logout", logout_path, style: "text-decoration: underline;" %>
      <% if current_user.profile %>
        <%= link_to "Edit Your Profile", edit_profile_path(profile_id: current_user.profile.id), class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
      <% else %>
        <%= link_to "Make Your Profile", new_profile_path, class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
      <% end %>
    <% else %>
      <%= link_to "BECOME A GUIDE | LOGIN", signup_path, class: "btn btn-small btn-turquoise", style: "margin-left: 6px; padding: 6px 40px 5px 40px;" %>
    <% end %>    
  </div>
</div>

<!-- content -->
<div class="simple_container">
  <h2> What Guidelighter is </h2>
  <p>   
    Guidelighter is a peer to peer marketplace for personal mentoring, advice and guidance. Firstly, Guidelighter allows you to easily share your personal experience and expertise by becoming a guide. Secondly, you can legitimately request the support of all guides for your benefit. <br>
    <div style="text-align: center;">
      <%= link_to "Become a guide |", signup_path %> <%= link_to "Find guidance", search_path(category: "career_insights") %>
    </div>
  </p>

  <h2> Oleg </h2>
  <%= image_tag "oleg.jpg" %>
  <p> Born in the Soviet Union, grew up in Germany, living in London. Working in finance, team-player, Karma-addict. Good at looking for 
  trouble, better at finding solutions. Guidelighter is a brain-child that has been growing in my mind for years. It sometimes only takes the smallest of efforts to help a person in a major way. Why don’t more people do it then? Helping starts in your day to day. Let’s hack helping and raise people’s awareness of how we can make each other’s lives easier! <br>
  </p>

  <h2> Suro </h2>
  <%= image_tag "suro.jpg" %>
  <p>
    I'm a Co-Founder & CEO at Guidelighter and an Associate in the Healthcare M&A Team at Rothschild. I've worked for over four years advising corporates and private equity firms on M&A and capital markets transactions in the Healthcare and Industrials sectors at Rothschild and Citigroup. Having studied BSc. (Hons.) Accounting & Finance at the University of Warwick, I had a knack for entrepreneurship and started several businesses before which include: a presentation design & consultancy business, a mobile app focused on influencing savings and an online revision notes marketplace. I've mentored students and young professionals exploring career opportunities, looking to launch a start up, start a blog or share perspectives on the journey of becoming a better value investor. 
  </p>

  <h2> Johannes </h2>
  <%= image_tag "johannes.jpg" %>
  <p>
    I'm the CTO of Guidelighter, the very page you are on right now. That means that I do all the programming and development work around here. Despite my role as CTO I have never set foot in a Computer Science lecture, which is something I simultaneously regret and am proud of. Instead my formal education is in Economics. I hold a Bachelor in "Economics and Management" from the University of Oxford. The stuff with computers I mostly taught myself through trial and error. Generally I have a wide range of interests and can pretty much be interested in anything as long as there's something to figure out. Right now I'm figuring out how to make Guidelighter great for you.
  </p> <br>


  <h2> Guidelighter - Why </h2>
   <p>
    When making career or university decisions, all you sometimes need is a chat with someone who has been there and has done it. You shouldn’t be in the position of not having anyone to ask such important questions. <br> <br> 

    Guidelighter is the easy way to talk to such a person. We are a marketplace for students, professionals and firms to offer their experience, coaching or any other form of career/university advice & help to those who need it right now. <br> <br>

    All of us have valuable experience that others could benefit from. Therefore on Guidelighter, everyone can become a guide and share their knowledge and experience peer to peer on their own terms and at whatever price they deem appropriate – or for free. <br> <br>

    Our goal is to make many more people share experience and many more people to access experience before making important life and career decisions. Everyone deserves their personal career guide and Guidelighter is here to give you one!"
   </p> <br>
</div>

app/views/pages/home.html.erb
<div class="gl_header">
  <div class="links">
    <%= link_to "About Us", about_path %>
    <%= link_to "How it works", how_path %>
    <%= link_to "Blog", "https://medium.com/guidelighter", target: "_blank" %> 
    <%= link_to "Success Stories", reviews_path, style: "margin-right: 4px;" %>
    
    <% if logged_in? %>
      <%= link_to "Logout", logout_path, style: "text-decoration: underline;" %>
      <% if current_user.profile %>
        <%= link_to "Edit Your Profile", edit_profile_path(profile_id: current_user.profile.id), class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
      <% else %>
        <%= link_to "Make Your Profile", new_profile_path, class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
      <% end %>
    <% else %>
      <%= link_to "BECOME A MENTOR YOURSELF", signup_path, class: "btn btn-small ", style: "margin-left: 6px; padding: 6px 22px 5px 22px; border: 1px solid white;" %>
    <% end %>    
  </div>
</div>


<div class="home_container" style="height: 1948px;">
  <div class="image_background"> </div>
  <div class="color_background"> </div>

  <!-- search 
  <div class="btn-on-show">
    <input id="search_form" type="text" name="search" placeholder="type to search" onkeyup="executeSearch();" style="margin-right: 5px;" />
  </div> -->

  <!-- Intro  -->
  <div class="intro">
    <p class="centered"> <%= notice %> </p>
    <!-- <h2 id="gl_slogan"> Personal guidance from real people <br> who care </h2> -->

    <!-- <h2 id="gl_slogan"> Find and connect with the Mentors <br> who have the career you want. </h2> -->
    <h2 id="gl_slogan"> Get the immediate, personal help of real Mentors who care. </h2>

    <!-- <h2 id="gl_slogan"> Find Mentors who have the career you want. Easily request their support. </h2> -->
    
    <p id="sub_slogan" style="text-align: center; font-size: 22px;"> Personal Mentoring <i class="fa fa-check" aria-hidden="true" style="color: #E59667;"></i> Help with Applications <i class="fa fa-check" aria-hidden="true" style="color: #E59667;"></i> 
    </p>

    <div class="button" style="margin-top: -30px;">    
      <div style="height: 30px;">
        <div class="fb-like" data-href="https://www.facebook.com/Guidelighter/?fref=ts" data-width="100px" data-layout="standard" data-action="like" data-show-faces="false" data-share="true" style="padding-top: 10px;"></div>
      </div>
    </div> <br>

      <!-- 
        <div style="font-size: 15px; width: 470px; text-align: center; margin: 0px 200px;">
        <h3 style="float: left; font-size: 22px;"> Get Mentor Support </h3>
        <%= form_for :message, url: contact_path do |f| %>
          <%= f.text_area :user_input, placeholder: "Briefly describe your situation. We will email you with a suggestion of 3 of our mentors who can help you out.", style: "height: 75px;" %>
          <%= f.text_field :email, placeholder: "you@gmail.com", style: "width: 100%;" %>
          <%= f.submit "Done.", id: "std-btn", style: "margin-top: 5px; padding: 7px 55px;" %>
        <% end %>
      </div>
      -->

    <h3 style="padding-top: 18px; padding-bottom: 1px; line-height: 1.35; font-size: 23px; text-decoration: underline; border: none;"> 
      Industry categories to find your guide:
    </h3>
      <!-- <%= link_to "or click to request a free consultation.", request_consultation_path, style: "padding: 8px 10px 8px 4px; margin-left: 0px; font-size: 18px;" %></h3> -->
  </div>

  <div style="text-align: center; margin-top: -28px;">
    <% {"Management Consulting" => "consulting", "Banking & Trading" => "banking_and_trading", "Finance & Accounting" => "finance_accounting","Entrepreneurship" => "entrepreneurship", "Freelancers & Digital Nomands" => "freelancer_digital", "Programming" => "programming_development", "Product Management" => "product_management", "Marketing & Sales" => "marketing_sales", "NGOs & Politics" => "ngos_politics", "Academic Careers" => "academic_careers", "Teaching" => "teaching", "Consumer Goods industry" => "consumer_goods", "Art, Design, Theatre, Film & Graphics" => "arts", "Sciences & Engineering" => "sciences_engineering", "Hospitality & Travel" => "hospitality", "Journalism" => "journalism", "Healthcare" => "healthcare", "Personal Coaching" => "coaching", "MBA" => "mba", "Professional Examinations" => "professional_exams", "University Application Help" => "university_applications_exams"}.each do |name, category| %>
      <%= link_to "#{name}", profile_search_path(category: "#{category}"), class: "btn btn-lg tag-btn", style: "font-size: 12px; padding: 11px 17px; margin: 1px; z-index: 1000;" %>
    <% end %>
      <% if @search_results %>
        <h3 style="padding-top: 0px; padding-bottom: 1px; line-height: 1.35; font-size: 23px; text-decoration: underline; border: none; float: left;"> Find your guide below | Category you have chosen: <%= @category.capitalize %> </h3>
      <% else %>
        <h3 style="padding-top: 0px; padding-bottom: 1px; line-height: 1.35; font-size: 23px; text-decoration: underline; border: none; float: left;"> Examples: Some of our 289 guides who recently helped someone out </h3>
      <% end %>
  </div> <br> <br>

  <!-- search results, if any. -->
  <% if @search_results %>
    <div style="position: relative;">
      <% @search_results.each do |profile| %>
          <%= link_to show_profile_path(profile_id: profile) do %>
            <div class="listing" style="background-color: #F5EFE6;">
              <!-- Image -->
              <% unless profile.profile_image.url.nil? %> 
                  <div class="centered"> <%= image_tag profile.profile_image.url %> </div>
              <% end %>

              <!-- Name -->
              <div id="listing_name"> 
                <h4 style="margin-bottom: 16px;"> <%= profile.advisor.first_name if profile.advisor %> <%= profile.advisor.second_name[0] if profile.advisor %>. </h4>
                <h4> <%= profile.job_title if profile.job_title %> </h4>
                </h4> 
              </div>
              <!-- Bottom -->
              <div id="listing_bottom"> 
                <span class="bottom">              
                  <%= link_to "Request #{profile.advisor.first_name} | £ #{profile.advisor.profile.session_price} per session", "#" %> 
                </span>
              </div>
            </div>
          <% end %>
      <% end %>
    </div>
  <% end %>

  <!-- listings -->
  <div style="position: relative; margin-top: -26px;">
  <% @advisors.each do |advisor| %>
    <% if advisor && advisor.profile && advisor.listings %>

      <%= link_to show_profile_path(profile_id: advisor.profile) do %>
        <div class="listing">
          <!-- Image -->
          <% unless advisor.profile.nil? %>  
            <% unless advisor.profile.profile_image.url.nil? %> 
                <div class="centered"> <%= image_tag advisor.profile.profile_image.url %> </div>
            <% end %>
          <% end %>
          <!-- Name -->
          <div id="listing_name"> 
            <h4 style="margin-bottom: 16px;"> <%= advisor.first_name %> <%= advisor.second_name[0] %>. </h4>
            <h4> <%= advisor.profile.job_title %> </h4>
            </h4> 
          </div>
          <!-- Bottom -->
          <div id="listing_bottom"> 
            <span class="bottom">              
              <%= link_to "Request #{advisor.first_name} | £ #{advisor.profile.session_price} per session", "#" %> 
            </span>
          </div>
        </div>
      <% end %>

    <% end %>
  <% end %>
  </div>
 
  <div class="bottom_right_buttons_home">
    <%= link_to "Request Free Chat", request_consultation_path, class: "btn btn-md", style: "width: 208px;" %>
  </div>
</div>

<% unless @category %> 
  <div class="gl_footer" style="text-align: center; padding-top: 8px;">
    <div style="width: 800px; margin: 0px auto;">
      <%= link_to "Get Mentor support.", "", onclick: "return move_up();", style: "font-size: 26px; border: 2px solid white; padding: 18px 62px;; color: white;" %>  
      <!-- <%= link_to "Browse through our guides by category.", "", onclick: "return move_up();", style: "font-size: 26px; border: 2px solid white; padding: 18px 62px;; color: white;" %> -->
    </div>  
  </div>
<% end %>


<script type="text/javascript">
(function(d, s, id) {
  window.Wishpond = window.Wishpond || {};
  Wishpond.merchantId = '1010063';
  Wishpond.writeKey = 'ef80972ca880';
  var js, wpjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//cdn.wishpond.net/connect.js";
  wpjs.parentNode.insertBefore(js, wpjs);
}(document, 'script', 'wishpond-connect'));
</script>

<script type="text/javascript">
  function move_up() {
    location.href = "#";
    location.href = "#sub_slogan";
    return false;
  }

  function executeSearch(){
    setTimeout(function(){
      search_value = document.getElementById('search_form').value;
      find(search_value);
    }, 2100);
  }

  function showApplicationTags(){
    // show subtags & hide others
    $("#career_insights_subtags").css("display", "none");
    $("#practical_expertise_subtags").css("display", "none");
    $("#application_help_subtags").fadeIn(500);
    // colorize button & normalize others
    $("#applications_category").css("background-color", "#E49362");
    $("#insights_category").css("background-color", "#F5EFE6");
    $("#practical_category").css("background-color", "#F5EFE6");
  };

  function showCareerInsightsTags(){
    // show subtags & hide others
    $("#application_help_subtags").css("display", "none");
    $("#practical_expertise_subtags").css("display", "none");  
    $("#career_insights_subtags").fadeIn(500);
    // colorize button & normalize others
    $("#applications_category").css("background-color", "#F5EFE6");
    $("#insights_category").css("background-color", "#E49362");
    $("#practical_category").css("background-color", "#F5EFE6");  };

  function showPracticalExpertiseTags(){
    // show subtags & hide others
    $("#application_help_subtags").css("display", "none");
    $("#career_insights_subtags").css("display", "none");
    $("#practical_expertise_subtags").fadeIn(500);
    // colorize button & normalize others
    $("#applications_category").css("background-color", "#F5EFE6");
    $("#insights_category").css("background-color", "#F5EFE6");
    $("#practical_category").css("background-color", "#E49362");
  };
</script>

app/views/pages/how.html.erb
<!-- header -->
<div class="gl_header">
  <div class="links">
    <%= link_to "About Us", about_path %>
    <%= link_to "Success Stories", reviews_path %>
    <%= link_to "Blog", "https://medium.com/guidelighter", target: "_blank" %> 
    <%= link_to "Terms & Conditions", terms_path %>

    <% if logged_in? %>
      <%= link_to "Logout", logout_path, style: "text-decoration: underline;" %>
      <% if current_user.profile %>
        <%= link_to "Edit Your Profile", edit_profile_path(profile_id: current_user.profile.id), class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
      <% else %>
        <%= link_to "Make Your Profile", new_profile_path, class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
      <% end %>
    <% else %>
      <%= link_to "BECOME A GUIDE | LOGIN", signup_path, class: "btn btn-small btn-turquoise", style: "margin-left: 6px; padding: 6px 40px 5px 40px;" %>
    <% end %>
  </div>
</div>
<!--content  -->
<div class="simple_container">
  <h2> What Guidelighter is </h2>
  <p style="margin-bottom: 20px;">   
    Guidelighter is a peer to peer marketplace for personal mentoring, advice and guidance. Firstly, Guidelighter allows you to easily share your personal experience and expertise by becoming a guide. Secondly, you can legitimately request the support of all guides for your benefit. <br>
    <div style="text-align: center;">
      <%= link_to "Become a guide |", signup_path %> <%= link_to "Find guidance", search_path(category: "career_insights") %>
    </div>
  </p>  
<br>  <iframe width="560" height="315" src="https://www.youtube.com/embed/-27ykz_2JOo" frameborder="0" allowfullscreen></iframe>
  <br> <br>
  <h2> How Guidelighter works in detail </h2>
    <p> On the one hand people can share their personal advice, mentorship and guidance in a certain regard and get paid for doing so. This  may involve things like career advice about their current or past profession, help with applications and CVs, general mentoring or the teaching a specific skill. On the other hand people who are in need for such guidance, can easily and legitimately request it from the guides listed on Guideligher.
    </p>

  <h2> FAQs - Guides </h2>
  <p class="faq_question">  How much should I charge? </p>
  <div class="faq_answer" > This is entirely up to you and what you feel your time and listing are worth. A good indicator would normally be to compare yourself to similar listings on the marketplace. But there is no right or wrong price as it depends entirely on you! </div>
 
  <p class="faq_question"> Does my work contract permit me to be a guide on Guidelighter? </p>
  <div class="faq_answer"> If in doubt we encourage you to check with your employer. In certain cases, you may need your employers’ permission to discuss your company’s application process. What we would advise in such cases would be to focus on your other experience not linked to your particular employer (university or industry related). </div>
 
  <p class="faq_question"> Is there any type of information I should not share with my mentee or could there be any compliance issues in general? </p>
  <div class="faq_answer"> As per our Terms & Conditions, you are not allowed to share any confidential and non-public information with any user. </div>

  <p class="faq_question"> Are there any experiences or listings I should not share? </p>
  <div class="faq_answer"> Guidelighter is currently focusing on career, entrepreneurship and university application advice. You should only post listings that can broadly be included under these topics. Should any listings be posted that are completely outside of these areas, we will contact the respective guide and ultimately reserve the right to remove such listings. </div>
 
  <p class="faq_question"> How should I report any earnings I make on Guidelighter for tax purposes? </p>
  <div class="faq_answer"> Any earnings you make through Guidelighter would be considered self-employed income. Different countries have different thresholds for such income before you must pay taxes. We recommend you check with your country’s respective tax authorities if in doubt. </div>
 
  <p class="faq_question"> How should I communicate with my Mentee? </p>
  <div class="faq_answer"> The initial communication is usually made via email. You can communicate with a user once the user has completed a payment and as long as the guidance is ongoing. We encourage guides and users to agree on the most convenient form of communication for both sides be it a coffee meeting, internet-video chat or email exchange. Guidelighter will include on-platform communication in a later version. </div>
 
  <p class="faq_question"> My Profession is X – can I still sign up as a Guide? </p>
  <div class="faq_answer"> Yes! We firmly believe in the principle that every experience that you have may be valuable to someone else. </div>

  <p class="faq_question"> I would like to donate my earnings to charity. Can I do this via Guidelighter? </p>
  <div class="faq_answer"> A later version of Guidelighter will include an integration of Justgiving to give you the option to directly choose a charity you would like to support. Until then we would ask you to drop us an email at founders@guidelighter.com indicating your wish for your earnings to go to a charity of your choice and we will ensure that any earnings you make are immediately transferred over. </div>
  
  <p class="faq_question"> How do I get paid? </p>
  <div class="faq_answer"> 
   Once your guidance session is completed, we will transfer your earnings across to you immediately subject to a 20% Guidelighter charge and any PayPal payment processing fees.
  </div>
 

  <h2> FAQs - Requesting Users </h2>
  <p class="faq_question"> What if my guide does not respond to me? </p>
  <div class="faq_answer"> 
    Many of our guides are extremely busy people so you might want to give them a few days to get in touch. They will be receiving email reminders about your request. Should you still not hear from your guide within one week of making the payment, we would ask you to send us an email on founders@guidelighter.com and we will help you resolve any existing issue.
   </div>   

  <p class="faq_question"> How should I approach my guide? </p>
  <div class="faq_answer"> 
    We will put you in touch via email and suggest you take it from there. We suggest that you then agree on the best form of communication (coffee, call, email or whatever you feel is most appropriate) directly with your guide. And don’t worry – our guides are nice people! ;-)
   </div>   

  <p class="faq_question"> I am not satisfied with my Guide – what should I do? </p>
  <div class="faq_answer"> 
    Share a review with us to highlight the areas of the guidance you were not satisfied with. If you feel that anything happened that we should know about, please email us on founders@guidelighter.com
   </div>   

  <p class="faq_question"> The experience I am looking for is not available on Guidelighter, is there anything you can do? </p>
  <div class="faq_answer"> 
    Sorry about that. Do let us know what you are looking for and we will see what we can do. As Guidelighter is growing, make sure to come back again to check our growing list of guides and experiences on offer.
  </div>

  <h2> FAQs - General </h2>
  <p class="faq_question"> In which countries is Guidelighter available? </p>
  <div class="faq_answer"> 
    Guidelighter is not geographically limited and regardless where you are based are welcome to post listings or request guides.
   </div>   
  <p class="faq_question"> How long is a session? </p>
  <div class="faq_answer"> 
    It depends. We encourage Guides to provide a detailed overview of what they will be offering in their listing to avoid any misunderstanding. However, we do not believe that mentoring or any form of experience sharing should be sold by the clock so hence a session is as long as the Guide specifies and/or as long as needed.
   </div>   
  <p class="faq_question"> Shouldn’t career advice and guidance be free of charge? </p>
  <div class="faq_answer"> 
    There are free listings on Guidelighter but ultimately, our goal is to raise the game in terms of access to career and university application advice for everyone and for that busy professionals need to have certain incentives. It also helps for guidance-seekers to demonstrate some commitment for the valuable advice they receive.
  </div>
</div>

app/views/pages/successful_signup.html.erb
<div class="gl_header">
  <div class="links">
    <%= link_to "Contact Us", contact_path, class: "btn white_border" %>
    <%= link_to "EXPLORE LISTINGS", search_path(category: "career_insights"), class: "btn white_border" %>
  </div>
</div>

<div class="simple_container">
  <!-- signup loader -->
  <div class="signup_loader">
    <%= image_tag "page-loader.gif" %>
    <p> We are processing your request. <br> One second. </p>
  </div> 
  <!-- setting background color -->
  <div class="color_background"> </div>
  <!-- content -->
  <br> <br> <br>
  <div style="color: grey; margin-bottom: 5px;"> <%= notice %> </div>
  <div class="grey_box">  
    <br>
    <p> 
      Thank you very much for becoming a guide. We will get in touch once your guidance is being requested. If you like, you can watch funny Youtube videos now. You have earned it.
    </p>
    <div class="button">
      <a href="https://www.youtube.com/watch?v=BtG33gP-j6E" id="std-btn"> Funny Cats on Youtube </a>
    </div>
  </div> 
  <!-- love -->
  <div class="with_love">
    Made with <i class="fa fa-heart" aria-hidden="true"></i> in Barcelona
  </div>
</div>

<!-- js -->
<script type="text/javascript">
  // fadeOut signup_loader
  $(window).load(function() {
    $(".signup_loader").delay(3850).fadeOut("slow");
  })
</script>