config/routes.rb
Rails.application.routes.draw do

  root 'pages#home' # ROOT

  get 'about', to: 'pages#about', as: 'about' # RESOURCES
  get 'how', to: 'pages#how', as: 'how'
  get 'reviews', to: 'pages#reviews', as: 'reviews'
  get 'successful_signup', to: 'pages#successful_signup', as: 'successful_signup'
  get 'terms', to: 'pages#terms'
  get 'ambassadors', to: 'pages#ambassadors'
  get "newsletter", to: "pages#newsletter", as: "newsletter"

  # advisors
  get 'signup', to: 'advisors#signup', as: 'signup'
  post 'signup', to: 'advisors#signup_action', as: 'signup_action'

  # profiles
  get 'profile/:profile_id', to: 'profiles#show', as: 'show_profile'

  get 'new_profile', to: 'profiles#new_profile', as: 'new_profile'
  post 'new_profile', to: 'profiles#new_profile_action', as: "new_profile_action"

  get 'edit_profile', to: 'profiles#edit', as: 'edit_profile'
  patch 'update_profile', to: 'profiles#update', as: 'update_profile'


  # listings 
  get 'listing/:listing_id', to: 'listings#show', as: 'show_listing'
  
  get 'new_listing', to: 'listings#new_listing', as: "new_listing"
  post 'new_listing', to: 'listings#new_listing_action', as: "new_listing_action"
  
  get 'edit_listing/:listing_id', to: 'listings#edit', as: 'edit_listing'
  patch 'update_listing/:listing_id', to: 'listings#update', as: 'update_listing'

  delete 'delete_listing/:listing_id', to: 'listings#destroy', as: 'delete_listing'

  post 'question', to: 'listing_messages#create', as: 'question_message'

  # requests
  get 'request/:listing_id', to: "requests#new_request", as: 'new_request'
  post 'request/:advisor_id', to: 'requests#create_request', as: 'create_request'
  get 'request_successful', to: 'requests#successful_request', as: 'successful_request'

  # sessions
  get 'login', to: 'sessions#login', as: "login"
  post 'login', to: 'sessions#login_action', as: "login_action"
  get 'logout', to: 'sessions#logout', as: 'logout'

  # admin
  get 'admin', to: "admin_actions#admin", as: 'admin' # ADMIN
  get 'profiles_overview', to: "admin_actions#profiles_overview", as: "profiles_overview"

  get 'listings_overview', to: "admin_actions#listings_overview", as: "listings_overview"

  # advisor resources
  get 'advisors_resources/:advisor_id', to: "admin_actions#advisors_resources", as: "advisors_resources"

  # admin editing
  get 'admin_edit_profile/:profile_id', to: "admin_actions#admin_edit_profile", as: "admin_edit_profile"
  patch 'admin_update_profile', to: "admin_actions#admin_update_profile", as: "admin_update_profile"

  get "admin_edit_listing/:listing_id", to: "admin_actions#admin_edit_listing", as: "admin_edit_listing"
  patch 'admin_update_listing/:listing_id', to: "admin_actions#admin_update_listing", as: "admin_update_listing"

  # admin deletting
  delete 'destroy_advisor/:advisor_id', to: "admin_actions#destroy_advisor", as: 'admin_destroy_advisor'

  # tagging by admin
  # get "tagging", to: "admin_actions#tagging", as: "tagging"
  # post "update_tags/:listing_id", to: "admin_actions#update_tags", as: "update_tags"
  get "profile_tagging", to: "admin_actions#profile_tagging", as: "profile_tagging"
  post "update_profile_tags/:profile_id", to: "admin_actions#update_profile_tags", as: "update_profile_tags"


  # functionalities
  # contacts
  get 'contact', to: 'contact_messages#new', as: 'contact' # FUNCTIONALITIES
  get 'request_consultation', to: 'contact_messages#request_consultation', as: 'request_consultation'
  post 'contact', to: 'contact_messages#create', as: 'create_contact'
  get 'new_user_request', to: 'contact_messages#new_user_request', as: 'new_user_request'

  # pw reset
  get 'new_password_request', to: 'contact_messages#new_password_request', as: 'new_password_request'
  post 'pw_retrieval_email', to: 'contact_messages#pw_retrieval_email', as: 'pw_retrieval_email'
  
  get 'pw_reset/:pw_reset_identifier', to: 'advisors#pw_reset', as: 'pw_reset'
  patch 'pw_reset_action/:advisor_id', to: "advisors#pw_reset_action", as: "pw_reset_action"

  # search
  get "search", to: "search#get_results", as: "search"
  get "profile_search", to: "search#profile_search", as: "profile_search"

end

app/helpers/listingsfilter_helper.rb
module ListingsfilterHelper
end

app/views/listingsfilter/find_listings.html.erb
<div class="gl_header">
  <% if logged_in? %>
    <div class="links">
      <%= link_to "What people say", reviews_path %>
      <%= link_to "About Us", about_path %>
      <%= link_to "Contact Us", contact_path %>
      <%= link_to "How It Works", how_path %>
      <%= link_to "Edit Profile", edit_profile_path %>
      <%= link_to "Post Listing", new_listing_path %>
      <%= link_to "Manage Listings", new_listing_path %>
      <%= link_to "Admin", admin_path if Rails.env.development? %>
      <%= link_to "Logout", logout_path, class: "btn btn-small btn-turquoise" %>
    </div>
  <% else %>
    <div class="links">
      <%= link_to "What people say", reviews_path %>
      <%= link_to "About Us", about_path %>
      <%= link_to "Contact Us", contact_path %>
      <%= link_to "How It Works", how_path %>
      <%= link_to "Login", login_path %>
      <%= link_to "Admin", admin_path if Rails.env.development? %>
      <%= link_to "Guide Signup", signup_path %>
      <%= link_to "What are you looking for?", new_user_request_path, class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
    </div>
  <% end %>
</div>


<div class="home_container">
  <div class="image_background"> </div>
  <div class="color_background"> </div>

  <div class="intro" style="margin-bottom: 10px;">
    <!-- Listings -->
    <br>
    <% if @search == "application_help" %>
      <h2 style="font-size: 36px; text-align: center;"> Application Help <span style="font-size: 11px;"> </span> </h2>
    <% elsif @search == "career_insights" %>
      <h2 style="font-size: 36px; text-align: center;"> Career Insights <span style="font-size: 11px;"> </span>  </h2>
    <% else %>
      <h2 style="font-size: 36px; text-align: center;"> Practical Expertise <span style="font-size: 11px;"> </span>  </h2>
    <% end %>

    <div style="margin-bottom: 0px;">
      <% if @search == "application_help" %>
        <%= link_to "Application Help", find_listings_path(search: "application_help"), class: "btn btn-lg tag-btn", style: "width: 33%; background-color: #E49362;" %>
      <% else %>
        <%= link_to "Help with your Application", find_listings_path(search: "application_help"), class: "btn btn-lg tag-btn", style: "width: 33%;" %>
      <% end %>

      <% if @search == "career_insights" %>
        <%= link_to "Insights into Career Paths", find_listings_path(search: "career_insights"), class: "btn btn-lg tag-btn", style: "width: 33%; background-color: #E49362;" %>
      <% else %>
        <%= link_to "Insights into Career Paths", find_listings_path(search: "career_insights"), class: "btn btn-lg tag-btn", style: "width: 33%;" %>
      <% end %>
      
      <% if @search == "practical_expertise" %>
        <%= link_to "Practical Expertise Offers", find_listings_path(search: "practical_expertise"), class: "btn btn-lg tag-btn", style: "width: 33%; background-color: #E49362;" %> <!-- old color: #FFD990 -->
      <% else %>
        <%= link_to "Practical Expertise Offers", find_listings_path(search: "practical_expertise"), class: "btn btn-lg tag-btn", style: "width: 33%;" %>
      <% end %>
    </div>
  </div>

  <% if @search == "application_help" %>
    <div class="subtags_on_searchpage" style="text-align: center;">
      <%  {"accounting" => "Accounting","art_school" => "Art School", "oxford" => "Oxford","asset_management" => "Asset Management","audit" => "Auditing","banking" => "Banking","big4" => "Big4","biochemistry" => "Biochemistry","business_school" => "Business School","cambridge" => "Cambridge","phd" => "PhD","ucl" => "UCL" ,"world_bank" => "World Bank","wharton" => "Wharton","university_application" => "University Applications","travel_industry" => "Travel Industry","sales_careers" => "Sales","un" => "UN","scholarships" => "Scholarships","trading" => "Trading","theatre" => "Theatre","think_tanks" => "Think Tanks","product_management" => "Product Management", "politics" => "Politics","neuroscience" => "Neuroscience","teaching" => "Teaching","personal_statement" => "Personal Statements","ngos" => "NGOs","nonprofit" => "Non-profits","case_studies" => "Case Studies","management_consulting" => "Management Consulting", "mathematics" => "Mathematics","humanitarian_careers" => "Humanitarian Careers","m&a" => "M&A","mba" => "MBA","mckinsey" => "McKinsey","hospitality" => "Hospitality","hr" => "HR","life_sciences" => "Life Sciences","international_relations"=> "International Relations","investment_banking" => "Investment Banking","interviews" => "Interview Prep","finance" => "Finance","healthcare" => "Healthcare","grad_school" => "Grad School","gmat" => "GMAT","history" => "History","grande_ecoles" => "Grand Ecoles","fintech" => "Fintech","funding_applications" => "Funding Applications","fraud_investigation" => "Fraud Investigation","games_industry" => "Games Industry","economic_consulting" => "Economic Consulting","economics" => "Economics","diplomacy" => "Diplomacy", "cv" => "CV","yale" => "Yale"}.each do |tag, name| %>
        <!-- generating links --> 
        <%= link_to "#{name}", find_listings_path(search: "#{tag}"), class: "btn btn-lg tag-btn", style: "font-size: 11px; padding: 8px 10px; margin: 1px; z-index: 1000;", :remote => true %>
      <% end %> 
      <%= link_to "All Application Help Offers", find_listings_path(search: "application_help"), class: "btn tag-btn btn-mild-highlight" %>
      <%= link_to "Make a particular request", new_user_request_path, class: "btn tag-btn btn-mild-highlight" %>
    </div>
  <% end %>

  <div id="tag_search_results" style="display: none;">
    <%= render "looping_through_results" %>
  </div>

  <div class="general_results" style="display: block;">
    <%= render "looping_through_results" %>
  </div>
</div>

app/views/listingsfilter/search_results.html.erb
<div class="gl_header">
  <% if logged_in? %>
    <div class="links">
      <%= link_to "What people say", reviews_path %>
      <%= link_to "About Us", about_path %>
      <%= link_to "Contact Us", contact_path %>
      <%= link_to "How It Works", how_path %>
      <%= link_to "Edit Profile", edit_profile_path %>
      <%= link_to "Post Listing", new_listing_path %>
      <%= link_to "Manage Listings", new_listing_path %>
      <%= link_to "Admin", admin_path if Rails.env.development? %>
      <%= link_to "Logout", logout_path, class: "btn btn-small btn-turquoise" %>
    </div>
  <% else %>
    <div class="links">
      <%= link_to "What people say", reviews_path %>
      <%= link_to "About Us", about_path %>
      <%= link_to "Contact Us", contact_path %>
      <%= link_to "How It Works", how_path %>
      <%= link_to "Login", login_path %>
      <%= link_to "Admin", admin_path if Rails.env.development? %>
      <%= link_to "Guide Signup", signup_path %>
      <%= link_to "What are you looking for?", new_user_request_path, class: "btn btn-small btn-turquoise", style: "margin-left: 18px;" %>
    </div>
  <% end %>
</div>

<!-- 
  get tags right
  - implement the right tags in backend (gather disperse ones - like consulting, management consulting)
  - add missing ones / get rid of some
  - approach: look at the listings in each category (application help) - then give tags

  get search right
  - implement search (as in superb category and subtag category together. Search needs to find listings that have tags "category" and "subcategory")  / also discrimnating serach - as in making it work (as for now art turns up all things where tags has art in it)

  get page dependent on serach right
  - empty page problem
  - title of each search result page
  - which buttons are highlighted
  - subtitle (as in title further down)
  - generall how things should look dependent on serach
-->

<div class="home_container">
  <div class="image_background"> </div>
  <div class="color_background"> </div>

  <div class="intro" style="margin-bottom: 10px;">
    <!-- Listings -->
    <br>
    <% if @search == "application_help" %>
      <h2 style="font-size: 36px; text-align: center;"> Application Help <span style="font-size: 11px;"> </span> </h2>
    <% elsif @search == "career_insights" %>
      <h2 style="font-size: 36px; text-align: center;"> Career Insights <span style="font-size: 11px;"> </span>  </h2>
    <% else %>
      <h2 style="font-size: 36px; text-align: center;"> Practical Expertise <span style="font-size: 11px;"> </span>  </h2>
    <% end %>

    <div style="margin-bottom: 0px;">
      <% if @search == "application_help" %>
        <%= link_to "Application Help", find_listings_path(search: "application_help"), class: "btn btn-lg tag-btn", style: "width: 33%; background-color: #E49362;" %>
      <% else %>
        <%= link_to "Help with your Application", find_listings_path(search: "application_help"), class: "btn btn-lg tag-btn", style: "width: 33%;" %>
      <% end %>

      <% if @search == "career_insights" %>
        <%= link_to "Insights into Career Paths", find_listings_path(search: "career_insights"), class: "btn btn-lg tag-btn", style: "width: 33%; background-color: #E49362;" %>
      <% else %>
        <%= link_to "Insights into Career Paths", find_listings_path(search: "career_insights"), class: "btn btn-lg tag-btn", style: "width: 33%;" %>
      <% end %>
      
      <% if @search == "practical_expertise" %>
        <%= link_to "Practical Expertise Offers", find_listings_path(search: "practical_expertise"), class: "btn btn-lg tag-btn", style: "width: 33%; background-color: #E49362;" %> <!-- old color: #FFD990 -->
      <% else %>
        <%= link_to "Practical Expertise Offers", find_listings_path(search: "practical_expertise"), class: "btn btn-lg tag-btn", style: "width: 33%;" %>
      <% end %>
    </div>
  </div>

  <% if @search == "application_help" %>
    <div class="subtags_on_searchpage" style="text-align: center;">
      <%  {"accounting" => "Accounting","art_school" => "Art School", "oxford" => "Oxford","asset_management" => "Asset Management","audit" => "Auditing","banking" => "Banking","big4" => "Big4","biochemistry" => "Biochemistry","business_school" => "Business School","cambridge" => "Cambridge","phd" => "PhD","ucl" => "UCL" ,"world_bank" => "World Bank","wharton" => "Wharton","university_application" => "University Applications","travel_industry" => "Travel Industry","sales_careers" => "Sales","un" => "UN","scholarships" => "Scholarships","trading" => "Trading","theatre" => "Theatre","think_tanks" => "Think Tanks","product_management" => "Product Management", "politics" => "Politics","neuroscience" => "Neuroscience","teaching" => "Teaching","personal_statement" => "Personal Statements","ngos" => "NGOs","nonprofit" => "Non-profits","case_studies" => "Case Studies","management_consulting" => "Management Consulting", "mathematics" => "Mathematics","humanitarian_careers" => "Humanitarian Careers","m&a" => "M&A","mba" => "MBA","mckinsey" => "McKinsey","hospitality" => "Hospitality","hr" => "HR","life_sciences" => "Life Sciences","international_relations"=> "International Relations","investment_banking" => "Investment Banking","interviews" => "Interview Prep","finance" => "Finance","healthcare" => "Healthcare","grad_school" => "Grad School","gmat" => "GMAT","history" => "History","grande_ecoles" => "Grand Ecoles","fintech" => "Fintech","funding_applications" => "Funding Applications","fraud_investigation" => "Fraud Investigation","games_industry" => "Games Industry","economic_consulting" => "Economics Consulting","economics" => "Economics","diplomacy" => "Diplomacy", "cv" => "CV","yale" => "Yale"}.each do |tag, name| %>
        <!-- generating links --> 
        <%= link_to "#{name}", find_listings_path(search: "#{tag}"), class: "btn btn-lg tag-btn", style: "font-size: 11px; padding: 8px 10px; margin: 1px; z-index: 1000;" %>
      <% end %> 
      <%= link_to "All Application Help Offers", find_listings_path(search: "application_help"), class: "btn tag-btn btn-mild-highlight" %>
      <%= link_to "Make a peticular request", new_user_request_path, class: "btn tag-btn btn-mild-highlight" %>
    </div>
  <% end %>

  <h6 style="text-decoration: underline;"> Application Help Offers - use the filters above to find what is useful to you. </h6>
  <!-- <h3> All Application Help Listings </h3> -->
  <% @listings.each do |listing| %>
    <% if listing.advisor && listing.advisor.profile %>
      <%= link_to show_listing_path(listing_id: listing) do %>
        
        <div class="listing">
          <!-- Image -->
          <% unless listing.advisor.profile.nil? %>  
            <% unless listing.advisor.profile.profile_image.url.nil? %> 
                <div class="centered"> <%= image_tag listing.advisor.profile.profile_image.url %> </div>
            <% end %>
          <% end %>
          <!-- Title -->
          <% unless listing.title.empty? %>
            <div id="listing_title"> <h4> <%= listing.title %> </h4> </div>
          <% end %>
          <!-- Bottom -->
          <div id="listing_bottom"> 
            <% unless listing.price.nil? %>
              <% unless listing.price == 0 %>
                <%= listing.advisor.first_name %> <%= listing.advisor.second_name[0] %>. |
                <%= link_to "Send Request |", new_request_path(listing_id: listing.id) %>
                <%= link_to "#{listing.price} £ ", new_request_path(listing_id: listing.id) %>
              <% else %>
                <%= listing.advisor.first_name %> <%= listing.advisor.second_name[0] %>. |
                <%= link_to "Send Request |", new_request_path(listing_id: listing.id) %>
                <%= link_to "Free", new_request_path(listing_id: listing.id) %>
              <% end %>
            <% end %>
          </div>
        </div>

      <% end %>
    <% end %>
  <% end %>
</div>